# "packageExtensions":
#  "react-element-to-jsx-string@15.0.0":
#    "dependencies":
#      "react-dom": "^18.3.1"
#  "tcompare@9.0.0":
#    "dependencies":
#      "react": "^18.3.1"
#  "@tapjs/test@4.0.0":
#    "dependencies":
#      "@types/node": "^22.9.0"
#  "@tapjs/typescript@3.0.0":
#    "dependencies":
#      "@types/node": "^22.9.0"
#      "typescript": "^5.6.3"

nodeLinker: node-modules
